### ISSUE TITLE
atomic plugin cannot be enabled

### ISSUE THREAD

**Issue by propriacausa** [mitre/atomic#11]
Hello,

I am using the stable version 2.7.0 of caldera and when I try to enable the atomic plugin, I receive the following error on the console:

> ERROR (c_plugin.py:71 enable) Error enabling plugin=atomic, 'NoneType' object is not iterable

I hope this helps you somehow to make caldera and its plugins even better.

**Comment by zaphodef** [comment]
should be fixed by #12

**Comment by Cyb3rWard0g** [comment]
I had to run the following for it to work properly with Caldera Master
```
git clone --recursive https://github.com/mitre/caldera.git ${CALDERA_HOME}
cd ${CALDERA_HOME} && git submodule update --recursive --remote
```

Otherwise you get the plugin at this commit https://github.com/mitre/atomic/commit/f0af6168e67a3f998a851de13bf8f53c640689e0  when you simply 

```
git clone --recursive https://github.com/mitre/caldera.git ${CALDERA_HOME}
```

```
Submodule path 'plugins/atomic': checked out 'f0af6168e67a3f998a851de13bf8f53c640689e0'
```

**Comment by propriacausa** [comment]
Thank you @zaphodef for the fix and thank you @Cyb3rWard0g for your instruction.
The plugin can be loaded now.
