### ISSUE TITLE
'NoneType' object is not iterable error at startup

### ISSUE THREAD

**Issue by pviossat** [mitre/atomic#13]
https://github.com/mitre/atomic/blob/f0af6168e67a3f998a851de13bf8f53c640689e0/app/atomic_svc.py#L91

Can cause 'NoneType' object is not iterable error at startup if json object doesn't have kill_chain_phases object

**Comment by wbooth** [comment]
@pviossat if you want to put up a PR to default to a dict on 91 if not present, we can fix that. I'm happy to do but you noticed it :)

**Comment by IOTech17** [comment]
> @pviossat if you want to put up a PR to default to a dict on 91 if not present, we can fix that. I'm happy to do but you noticed it :)

Could you please create the PR request, I need this issue to be fixed ASAP, as I am running test using the docker version (way easier to deploy than the default install method), and this is the last remaining bug preventing me from conducting some test using the Atomic plugin.

Thank you.

**Comment by pviossat** [comment]
Duplicate of #11. Seems to be already fixed, sorry.

**Comment by IOTech17** [comment]
> Duplicate of #11. Seems to be already fixed, sorry.

I can confirm that it is not fixed.

Deploying the latest version of Caldera the issue is still here.
