### ISSUE TITLE
Error to simulate TTPs from the Atomic

### ISSUE THREAD

**Issue by johnk3r** [mitre/atomic#18]
Hello, I'm starting to study Caldera and I have the following difficulty:

When I try to simulate an Atomic-related TTP, I am getting the following error message:

`import-module: The specified module 'PathToAtomicsFolder \ T1059.001 \ src \ SharpHound.ps1' has not been loaded because
no read module files found in any module directories.
...
(PathToAtomicsFo ... \ SharpHound.ps1: String) [Import-Module], FileNot
    FoundException
     + FullyQualifiedErrorId: Modules_ModuleNotFound, Microsoft.PowerShell.Commands.ImportModuleCommand`

I can see the imported TTP in the "/atomics" directory and the plugin was started with the server.
Where can I be wrong?

Congratulations for the project s2

**Comment by johnk3r** [comment]
Thanks.

As the installation automatically enabled Atomic I believed that there was no need for further configuration.

I will validate and return.

**Comment by clr2of8** [comment]
Note that Atomic Red Team sometime points to dependencies within its folder structure that do not exist until users run the "Prereq commands". I imagine this is why this particular atomic causes issues when imported into CALDERA as CALDERA tries to point to a file in the `src` directory that doesn't exist yet.  See the markdown of the atomic test here: https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1059.001/T1059.001.md#atomic-test-2---run-bloodhound-from-local-disk

Notice how one of the prereqs says that SharpHound must be found at `PathToAtomicsFolder\T1059.001\src\SharpHound.ps1` and this file is not in the redcanary atomic red team repo and would only be in the `src` directory after running the prereq commands. Perhaps the atomic plugin could run all the prereq commands before running the import.
