### ISSUE TITLE
no gui component to this plugin

### ISSUE THREAD

**Issue by ghost** [mitre/atomic#21]
How do I fix the problem given to me?

**Comment by wbooth** [comment]
Hi @veslo94 , no issue here -- its letting you know that the plugin doesn't come with a gui so there is nothing to see

**Comment by ghost** [comment]
Hello @wbooth :)
means abilities inside caldera, are these tests from the Atomic Red Team? Do I understand you correctly?) Sorry for such questions, I'm a student :)
