### ISSUE TITLE
Importing Atomic tests with comments spanning multiple lines

### ISSUE THREAD

**Issue by macmiranda** [mitre/atomic#24]
**What problem are you trying to solve? Please describe.**
> Any ideas on how to solve the [known issue](https://github.com/mitre/atomic#known-issues) of importing Atomic tests with comments spanning multiple lines, such as [Here-Strings](https://devblogs.microsoft.com/scripting/powertip-use-here-strings-with-powershell/)? 

**The ideal solution: What should the feature should do?**
> transparent compatibility between both projects

**What category of feature is this?**

- [ ] UI/UX
- [ ] API
- [x] Other

---------
- [x] Willing to submit a pull request to implement this feature?

Thank you!

**Comment by uruwhy** [comment]
Hi @macmiranda, apologies for the delay. CALDERA ability commands were not originally designed to handle comments, hence why we've marked it as a known issue for the atomic plugin. Improving compatibility would definitely be helpful between the atomic repo and CALDERA functionality.  I have potential ideas for fixes in mind, and I will let you know once a PR is in place. Thank you again for your patience and for using our tool!

**Comment by uruwhy** [comment]
This PR is currently in review and should address the comment issue: https://github.com/mitre/atomic/pull/26

**Comment by wbooth** [comment]
Stepping in for @uruwhy , the PR has been merged, if the issue persists please re-open this ticket or feel free to create a new one -- thanks!
