### ISSUE TITLE
Atomic is greyed out in menu, but is configured as a plugin in conf file

### ISSUE THREAD

**Issue by 0xd3vnull** [mitre/atomic#29]
I have an issue where the Atomic plugin is greyed out when I start Caldera using either the --insecure or with the local.yml environment file.

Stockpile is also greyed out.

The readme doesnt show any requirements, is there somewhere I can check error logs or is this a known issue.

I am running 4.0.0 on RHEL 8

**Comment by clenk** [comment]
Hi @0xd3vnull, thanks for the question. Those 2 plugins do not have a UI component and mostly just add abilities. So the plugins are working as expected! :)

Also there is some work in progress that will add minimal UI components for both of these plugins in the near future.

**Comment by 0xd3vnull** [comment]
Thanks for confirming this
