### ISSUE TITLE
lacking of dependencies converting

### ISSUE THREAD

**Issue by huangchen007** [mitre/atomic#30]
**Describe the bug**
Ability T1003.007 can't be execute on correct way because of lacking of dependencies like below when raw scripts in red team canary were converted to caldera scripts:

Do you guys have plan to fix that?  I found 134 abilities which had the same problems.

dependencies:
    - description: |
        Script to launch target process must exist
      prereq_command: |
        test -f #{script_path}
        grep "#{pid_term}" #{script_path}
      get_prereq_command: |
        echo '#!/bin/sh' > #{script_path}
        echo "sh -c 'echo \"The password is #{pid_term}\" && sleep 30' &" >> #{script_path}
    - description: |
        Requires Python
      prereq_command: |
        (which python || which python3 || which python2)
      get_prereq_command: |
        echo "Python 2.7+ or 3.4+ must be installed"

**To Reproduce**
none

**Expected behavior**
none

**Screenshots**

**Desktop (please complete the following information):**
all

**Additional context**
none

**Comment by huangchen007** [comment]
I would like to provide a path to fix the problem if you guys haven't  had a plan about that.

**Comment by uruwhy** [comment]
I'm looking at the corresponding ability in the atomic plugin, and it looks like things got imported correctly - I can see the correct payload being referenced. Was there a particular ability where you noticed the required payload was not included?

**Comment by huangchen007** [comment]
Ok，I explain it more detail.
In T1003.007.yaml, it needs /tmp/T1003.007.sh  at the first line while /tmp/T1003.007.sh isn't existing by default.
Actually it needs to be generated by "get_prereq_command" section first, but unfortunately atomics plugin don't do with get_prereq_command section.

**Comment by uruwhy** [comment]
I see what you mean now. I don't believe there are currently any plans underway to tackle these dependencies. What was the idea you had in mind?

**Comment by huangchen007** [comment]
Would you like to review it? @uruwhy

**Comment by uruwhy** [comment]
Thank you for your submission! Feel free to use this on your local installation if it meets your needs. Our team is discussing internally how to best address this issue - there is a possibility that we may end up converting the dependencies into separate standalone abilities to avoid cluttering the original ability commands with additional setup/dependency commands. Once we reach a decision and begin implementing a fix, I'll post it here

**Comment by huangchen007** [comment]
Looking forward to it!

**Comment by ArtificialErmine** [comment]
We've added support for dependencies as of #33. If the problem persists after this update, please feel free to reach out again and we'll see how we can help!
