### ISSUE TITLE
Atomic Plugin causes Caldera start up to hang

### ISSUE THREAD

**Issue by wkleinhenz** [mitre/atomic#36]
**Describe the bug**
When the Atomic plugin is enabled, Caldera doesn't advance past the _prepare_executor stage of the Atomic Plugin

**To Reproduce**
build a docker image using the instructions on the Caldera Github Repo
Enable the Atomic plugin using the local.yml file
run the Caldera server with the built image and the modified local.yml file using the docker-compose file provided in the Caldera Repo

**Expected behavior**
The Atomic plugin is enabled, and Caldera continues with initialization and start up

**Screenshots**
Screenshots of the error logs would be pretty large so ive included a paste bin of the error logs, https://pastebin.com/raw/V8dRw0Jg, for reference the last line was printed about 30 minutes before the creation of this ticket and is the last log to be printed

**Desktop (please complete the following information):**
 - OS: AlamaLinux 8.6 as the base OS, Caldera is running in Docker
 - Browser Edge
 - Version 4.0.0 of caldera, 2.7 of Atomic Plugin

**Additional context**

**Comment by mkultraWasHere** [comment]
@wkleinhenz - Stack trace of server.py command?
