### ISSUE TITLE
Parser app/parsers/atomic_powershell.py works incorrectly

### ISSUE THREAD

**Issue by Morpheme777** [mitre/atomic#37]
**Describe the bug**
parser _atomic_powershell_ mark every(almost) test as failed.

**To Reproduce**
1. Find the test _"Execute base64-encoded PowerShell from Windows Registry"_ and run it.
2. Test will be failed because of parser atomic_powershell.

**Expected behavior**
Test should be marked as successful if the output is equal to:
>VwByAGkAdABlAC0ASABvAHMAdAAgACIASABlAHkALAAgAEEAdABvAG0AaQBjACEAIgA=
>Hey, Atomic!

**Screenshots**
On the screenshot you can see the case. Test failed but it completed successfully
![image](https://user-images.githubusercontent.com/65189039/183666556-2b63167f-d6fc-4847-8faf-270723a2e2af.png)

**Desktop (please complete the following information):**
 - OS: 
```
analyst@ts-kali:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2021.2
Codename:       kali-rolling
```  
- atomic-plugin:
```
analyst@ts-kali:~/caldera$ cat plugins/atomic/VERSION.txt
2.9.0-2d766f82e65cb657e19b47afa9e8ba86
```  
- caldera:
```
v4.0.0
```  

**Additional context**
The reason of this behavior is `app/parsers/atomic_powershell.py`.
The line 6: `checked_flags = list('FullyQualifiedErrorId')` puts an array ['F', 'u', 'l', 'l, ..., 'o', 'l', 'd'] to variable checked_flags. In that case the following if-condition will be True because there is no any chances for output to not contain any of the symbols listed above.
To resolve the issue, I guess, that line 6 should looks like that: `checked_flags = ['FullyQualifiedErrorId']`

**Comment by mkultraWasHere** [comment]
@Morpheme777 reopen if still an issue.
