### ISSUE TITLE
Atomic plugin not supplying Caldera with activities

### ISSUE THREAD

**Issue by khr0x40sh** [mitre/atomic#5]
Upon start up, I have the following message:

```
2020-03-10 13:29:19 DEBUG    Ingested 0 abilities from Atomic plugin
2020-03-10 13:29:19 DEBUG    Enabled plugin: atomic
```
Atomic abilities while present in the plugin folder do not appear in Caldera as part of the "redcanary" technique set.

**Comment by khr0x40sh** [comment]
In caldera/plugins/atomic/atomic-red-team/atomics/ I have the yamls and the "T" directories.

**Comment by ghost** [comment]
Good find-- we had a bug in bleeding-edge code (shouldn't be a problem in the latest version 2.6.3). 

I just applied a fix to this repository to solve that problem. thanks!
